### ISSUE TITLE
Octave compatible?

### ISSUE THREAD

**Issue by stefano2734** [MarcHauptmann/fem#1]
Compatible to free matlab clone octave?
No license is needed for octave.

If yes, please extend your info in Readme with Octave Version. Actual Version of Octave is 7.2.
if unknown, untested with octave, info about  this also nice.
if no, it is also ok. Some commands are not compatible in octave.

**Comment by MarcHauptmann** [comment]
Thank you for your feedback! I think, with some minor tweaks the code would run in Octave. If you are interested, feel free to make it compatible and send a PR. I would appreciate your help!

**Comment by stefano2734** [comment]
I am a newbie in octave with interests for FEA and CFD.
Here some last infos about octave.
https://wiki.octave.org/Differences_between_Octave_and_Matlab
https://wiki.octave.org/Release_History
https://octave.org/NEWS-7.html

**Comment by MarcHauptmann** [comment]
I just made a quick check with Octave 6.4.0: `octave -p src/ --persist problem1_cubic.m` prints a nice diagram displaying the exact solution and the approximation. Other files also worked. It seems, that Octave misses `Polygon` which is used in `bem_square.m` line 14. A solution would be to implement it manually.
Also there seems to be a sign error in the solution `problem5.m`. But that should not be a problem related to Octave.

**Comment by stefano2734** [comment]
That is a nice result. 
You can write here in your readme.
works mostly with octave 6.4.
